### ISSUE TITLE
Unicode characters on web

### ISSUE THREAD

**Issue by nedtwigg** [sunny-chung/composable-table#6]
If I run `gradlew :demo:multiplatform-app:wasmJsBrowserDevelopmentRun` and open a browser I get this output

<img width="703" alt="image" src="https://github.com/sunny-chung/composable-table/assets/2924992/9070b077-032f-45a5-8b66-78f1707003c8">

as compared to this on the desktop:

<img width="795" alt="image" src="https://github.com/sunny-chung/composable-table/assets/2924992/00fe7953-aa08-40e4-9552-f6fe591634a5">

Great library!

**Comment by sunny-chung** [comment]
Thanks for opening an issue! Long time no see new issue reports.

This is due to an issue in Jetpack Compose Multiplatform:
https://github.com/JetBrains/compose-multiplatform/issues/3967

Currently, the workaround is to supply custom fonts and load into the UI.

I will update the demo to include the workaround.
